// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELPLNUMAxPnSjG-obTXcFPB3PsKfPeMQ',
    appId: '1:374076848111:web:9bd38adf4487c8dc64a81a',
    messagingSenderId: '374076848111',
    projectId: 'flutter-ecommerce-app-67bf2',
    authDomain: 'flutter-ecommerce-app-67bf2.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-67bf2.appspot.com',
    measurementId: 'G-5CE5S3YHXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jxA6TybLO7W-_cYrzwWRVuUYDto9iQE',
    appId: '1:374076848111:android:b342759c2c2e338964a81a',
    messagingSenderId: '374076848111',
    projectId: 'flutter-ecommerce-app-67bf2',
    storageBucket: 'flutter-ecommerce-app-67bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazf9Pj8jE5_9f6hB-kouNe03gSzE71Pg',
    appId: '1:374076848111:ios:1d8447d1cfa5286064a81a',
    messagingSenderId: '374076848111',
    projectId: 'flutter-ecommerce-app-67bf2',
    storageBucket: 'flutter-ecommerce-app-67bf2.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazf9Pj8jE5_9f6hB-kouNe03gSzE71Pg',
    appId: '1:374076848111:ios:9bf53e7738d84fb964a81a',
    messagingSenderId: '374076848111',
    projectId: 'flutter-ecommerce-app-67bf2',
    storageBucket: 'flutter-ecommerce-app-67bf2.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp.RunnerTests',
  );
}
